### ISSUE TITLE
Readme.md missing

### ISSUE THREAD

**Issue by Aniruddha09** [Astrophilic/my-first-blog#1]
Please add readme.md file!

**Comment by Astrophilic** [comment]
It is a very simple blog. 
Here are few inputs which you could follow

On you terminal, cd to the directory of this application and type following commands one by one:
	source myvenv/bin/activate
	python manage.py runserver
This will run the server on your computer
Now type the URL http://localhost:8000/ on your browser to see the blog!!!

**Comment by Aniruddha09** [comment]
Thanks @Astrophilic !
